# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5dd0e6c69453ba1e4258de12a58f1c5dc806f7349df1ff6d92b8dc615af58d62127cca7247a32e7d7f3de0ab74fcf988c81e34757fa0636fc551c75081eb211

test:
  secret_key_base: e71171c7c9fe74741fcaf9847d9bd8502cce4e1941465de08354ba3ef49846ef1931dd17203d397ee714fb92d2d2c83112a7a71290ffcaaaac9774c484fea6d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
